In [278]:
# - import libraries
# - load dataset
# - explore dataset

# - fix column names
# - fix individual columns

# - fix nulls in all type of columns
# - fix duplicates in all type of columns
# - fix outliers
# - fix logical intigrity
# - final exploration
# - save cleaned data

### 1. Import required libraries

In [279]:
import numpy as np
import pandas as pd

### 2. Load dataset

In [280]:
df = pd.read_csv(r"C:\Users\Arijit\Downloads\archive\Airbnb_Open_Data.csv", low_memory=False)
df

,id,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,...,service fee,minimum nights,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability 365,house_rules,license
0,1001254,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,...,$193,10.0,9.0,10/19/2021,0.21,4.0,6.0,286.0,Clean up and treat the home the way you'd like...,NaN
1,1002102,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,...,$28,30.0,45.0,5/21/2022,0.38,4.0,2.0,228.0,Pet friendly but please confirm with me if the...,NaN
2,1002403,THE VILLAGE OF HARLEM....NEW YORK !,78829239556,NaN,Elise,Manhattan,Harlem,40.80902,-73.94190,United States,...,$124,3.0,0.0,NaN,NaN,5.0,1.0,352.0,"I encourage you to use my kitchen, cooking and...",NaN
3,1002755,NaN,85098326012,unconfirmed,Garry,Brooklyn,Clinton Hill,40.68514,-73.95976,United States,...,$74,30.0,270.0,7/5/2019,4.64,4.0,1.0,322.0,NaN,NaN
4,1003689,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,...,$41,10.0,9.0,11/19/2018,0.10,3.0,1.0,289.0,"Please no smoking in the house, porch or on th...",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102594,6092437,Spare room in Williamsburg,12312296767,verified,Krik,Brooklyn,Williamsburg,40.70862,-73.94651,United States,...,$169,1.0,0.0,NaN,NaN,3.0,1.0,227.0,No Smoking No Parties or Events of any kind Pl...,NaN
102595,6092990,Best Location near Columbia U,77864383453,unconfirmed,Mifan,Manhattan,Morningside Heights,40.80460,-73.96545,United States,...,$167,1.0,1.0,7/6/2015,0.02,2.0,2.0,395.0,House rules: Guests agree to the following ter...,NaN
102596,6093542,"Comfy, bright room in Brooklyn",69050334417,unconfirmed,Megan,Brooklyn,Park Slope,40.67505,-73.98045,United States,...,$198,3.0,0.0,NaN,NaN,5.0,1.0,342.0,NaN,NaN
102597,6094094,Big Studio-One Stop from Midtown,11160591270,unconfirmed,Christopher,Queens,Long Island City,40.74989,-73.93777,United States,...,$109,2.0,5.0,10/11/2015,0.10,3.0,1.0,386.0,NaN,NaN
102598,6094647,585 sf Luxury Studio,68170633372,unconfirmed,Rebecca,Manhattan,Upper West Side,40.76807,-73.98342,United States,...,$206,1.0,0.0,NaN,NaN,3.0,1.0,69.0,NaN,NaN

### 3. Explore dataset

In [281]:
print("\nTotal rows : ", df.shape[0])
print("\nTotal columns : ", df.shape[1])
print("\nDataset size : ", df.size)
print("Info about dataset : \n", df.info())

Total rows :  102599

Total columns :  26

Dataset size :  2667574
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 102599 entries, 0 to 102598
Data columns (total 26 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   id                              102599 non-null  int64
 1   NAME                            102349 non-null  object
 2   host id                         102599 non-null  int64
 3   host_identity_verified          102310 non-null  object
 4   host name                       102193 non-null  object
 5   neighbourhood group             102570 non-null  object
 6   neighbourhood                   102583 non-null  object
 7   lat                             102591 non-null  float64
 8   long                            102591 non-null  float64
 9   country                         102067 non-null  object
 10  country code                    102468 non-null  object
 11  instant_bookable                102494 non-null  object
 12  cancellation_policy             102523 non-null  object
 13  room type                       102599 non-null  object
 14  Construction year               102385 non-null  float64
 15  price                           102352 non-null  object
 16  service fee                     102326 non-null  object
 17  minimum nights                  102190 non-null  float64
 18  number of reviews               102416 non-null  float64
 19  last review                     86706 non-null   object
 20  reviews per month               86720 non-null   float64
 21  review rate number              102273 non-null  float64
 22  calculated host listings count  102280 non-null  float64
 23  availability 365                102151 non-null  float64
 24  house_rules                     50468 non-null   object
 25  license                         2 non-null       object
dtypes: float64(9), int64(2), object(15)
memory usage: 20.4+ MB
Info about dataset :
 None

In [282]:
df.describe()

,id,host id,lat,long,Construction year,minimum nights,number of reviews,reviews per month,review rate number,calculated host listings count,availability 365
count,1.025990e+05,1.025990e+05,102591.000000,102591.000000,102385.000000,102190.000000,102416.000000,86720.000000,102273.000000,102280.000000,102151.000000
mean,2.914623e+07,4.925411e+10,40.728094,-73.949644,2012.487464,8.135845,27.483743,1.374022,3.279106,7.936605,141.133254
std,1.625751e+07,2.853900e+10,0.055857,0.049521,5.765556,30.553781,49.508954,1.746621,1.284657,32.218780,135.435024
min,1.001254e+06,1.236005e+08,40.499790,-74.249840,2003.000000,-1223.000000,0.000000,0.010000,1.000000,1.000000,-10.000000
25%,1.508581e+07,2.458333e+10,40.688740,-73.982580,2007.000000,2.000000,1.000000,0.220000,2.000000,1.000000,3.000000
50%,2.913660e+07,4.911774e+10,40.722290,-73.954440,2012.000000,3.000000,7.000000,0.740000,3.000000,1.000000,96.000000
75%,4.320120e+07,7.399650e+10,40.762760,-73.932350,2017.000000,5.000000,30.000000,2.000000,4.000000,2.000000,269.000000
max,5.736742e+07,9.876313e+10,40.916970,-73.705220,2022.000000,5645.000000,1024.000000,90.000000,5.000000,332.000000,3677.000000

### 4. Fix column names

In [283]:
# Step 1 - Explore columns
print(df.columns)

print("\nTotal columns : ", df.shape[1])
print("\nTotal duplicated columns : ", df.columns.duplicated().sum())
print("\nTotal unique columns : ", df.columns.nunique())

print("\nSpecial character containing columns : ", df.columns[df.columns.str.contains(r'[^A-Za-z0-9\s]')])
print("\nNumbers containing columns : ", df.columns[df.columns.str.contains(r'[0-9]')])
print("\nUpper case letters containing columns : ", df.columns[df.columns != df.columns.str.lower()])
print("\nLeft-right side Space containing columns : ", df.columns[df.columns != df.columns.str.strip()])
print("\nTotal Inner space containing columns : ", df.columns[df.columns.str.contains(' ')].nunique())

Index(['id', 'NAME', 'host id', 'host_identity_verified', 'host name',
       'neighbourhood group', 'neighbourhood', 'lat', 'long', 'country',
       'country code', 'instant_bookable', 'cancellation_policy', 'room type',
       'Construction year', 'price', 'service fee', 'minimum nights',
       'number of reviews', 'last review', 'reviews per month',
       'review rate number', 'calculated host listings count',
       'availability 365', 'house_rules', 'license'],
      dtype='object')

Total columns :  26

Total duplicated columns :  0

Total unique columns :  26

Special character containing columns :  Index(['host_identity_verified', 'instant_bookable', 'cancellation_policy',
       'house_rules'],
      dtype='object')

Numbers containing columns :  Index(['availability 365'], dtype='object')

Upper case letters containing columns :  Index(['NAME', 'Construction year'], dtype='object')

Left-right side Space containing columns :  Index([], dtype='object')

Total Inner space containing columns :  14

In [284]:
# Step 2 - Fix erros in those columns

df.columns = (
    df.columns
    .str.lower()
    .str.replace(' ', '_')
    .str.replace(r'[^A-Za-z_]', '', regex=True)
)

# Final Check
print("\nSpecial character containing columns : ", df.columns[df.columns.str.contains(r'[^A-Za-z0-9\s]')])
print("\nNumbers containing columns : ", df.columns[df.columns.str.contains(r'[0-9]')])
print("\nUpper case letters containing columns : ", df.columns[df.columns != df.columns.str.lower()])
print("\nTotal Inner space containing columns : ", df.columns[df.columns.str.contains(' ')].nunique())

print(df.columns)

Special character containing columns :  Index(['host_id', 'host_identity_verified', 'host_name', 'neighbourhood_group',
       'country_code', 'instant_bookable', 'cancellation_policy', 'room_type',
       'construction_year', 'service_fee', 'minimum_nights',
       'number_of_reviews', 'last_review', 'reviews_per_month',
       'review_rate_number', 'calculated_host_listings_count', 'availability_',
       'house_rules'],
      dtype='object')

Numbers containing columns :  Index([], dtype='object')

Upper case letters containing columns :  Index([], dtype='object')

Total Inner space containing columns :  0
Index(['id', 'name', 'host_id', 'host_identity_verified', 'host_name',
       'neighbourhood_group', 'neighbourhood', 'lat', 'long', 'country',
       'country_code', 'instant_bookable', 'cancellation_policy', 'room_type',
       'construction_year', 'price', 'service_fee', 'minimum_nights',
       'number_of_reviews', 'last_review', 'reviews_per_month',
       'review_rate_number', 'calculated_host_listings_count', 'availability_',
       'house_rules', 'license'],
      dtype='object')

In [285]:
# drop columns which is not important
columns_to_drop = [
    'reviews_per_month',
    'review_rate_number', 
    'calculated_host_listings_count', 
    'availability_',
    'house_rules', 
    'license', 
    'country_code', 
    'last_review'
]

df.drop(columns=columns_to_drop, inplace=True)
print("Total columns : ", df.shape[1])
print(df.columns)

Total columns :  18
Index(['id', 'name', 'host_id', 'host_identity_verified', 'host_name',
       'neighbourhood_group', 'neighbourhood', 'lat', 'long', 'country',
       'instant_bookable', 'cancellation_policy', 'room_type',
       'construction_year', 'price', 'service_fee', 'minimum_nights',
       'number_of_reviews'],
      dtype='object')

## 5. Fix individual columns
###    - Fix object type columns
###    - Fix int type columns

In [286]:
# Fix object type columns
# Step 1 - Explore every columns one by one

for column in df.columns:
    if df[column].dtype == "object":
        print(column)

name
host_identity_verified
host_name
neighbourhood_group
neighbourhood
country
instant_bookable
cancellation_policy
room_type
price
service_fee

In [287]:
for column in df.columns:

    if df[column].dtype == "object":

        if column == "instant_bookable":
            continue

        # Check for special characters - "!@#$%^&*()+-=[]{}|;':\",./<>?`~\\"
        print(
            f"Special characters in {column}: ",
            df[column].astype(str).str.contains(
                r'[^A-Za-z0-9\s]', regex=True, na=False
            ).sum()
        )

        # Check for numbers
        print(
            f"Numbers in {column}: ",
            df[column].astype(str).str.contains(
                r'[0-9]', regex=True, na=False
            ).sum()
        )

        # Check for Leading and trailing spaces in a string
        mask_spaces = df[column].notna() & (df[column] != df[column].str.strip())
        print(f"Spaces in {column} : ", mask_spaces.sum())

        # Check for upper case letters
        print(
            f"Uppercase-containing values in {column}: ",
            df[column].astype(str).str.contains(
                r'[A-Z]', regex=True, na=False
            ).sum()
        )

        print()

Special characters in name:  56821
Numbers in name:  34063
Spaces in name :  44
Uppercase-containing values in name:  101098

Special characters in host_identity_verified:  0
Numbers in host_identity_verified:  0
Spaces in host_identity_verified :  0
Uppercase-containing values in host_identity_verified:  0

Special characters in host_name:  4713
Numbers in host_name:  134
Spaces in host_name :  0
Uppercase-containing values in host_name:  102074

Special characters in neighbourhood_group:  0
Numbers in neighbourhood_group:  0
Spaces in neighbourhood_group :  0
Uppercase-containing values in neighbourhood_group:  102568

Special characters in neighbourhood:  13438
Numbers in neighbourhood:  0
Spaces in neighbourhood :  0
Uppercase-containing values in neighbourhood:  102583

Special characters in country:  0
Numbers in country:  0
Spaces in country :  0
Uppercase-containing values in country:  102067

Special characters in cancellation_policy:  0
Numbers in cancellation_policy:  0
Spaces in cancellation_policy :  0
Uppercase-containing values in cancellation_policy:  0

Special characters in room_type:  53701
Numbers in room_type:  0
Spaces in room_type :  0
Uppercase-containing values in room_type:  102599

Special characters in price:  102352
Numbers in price:  102352
Spaces in price :  102352
Uppercase-containing values in price:  0

Special characters in service_fee:  102326
Numbers in service_fee:  102326
Spaces in service_fee :  102326
Uppercase-containing values in service_fee:  0

In [288]:
# Special characters in name:  56821
# Numbers in name:  34063
# Leading/Trailing spaces in name:  294
# Uppercase-containing values in name:  101098

# Fix for column - name
df['name'] = (
    df['name']
    .str.strip()
    .str.lower()
    .str.replace(r'[^a-z\s]', '', regex=True)
    .str.strip()
)

In [289]:
# Check
print(df['name'].astype(str).str.contains(r'[^a-z\s]', regex=True).sum())
print(df['name'].astype(str).str.contains(r'[0-9]', regex=True).sum())

# We have to check those rows which contains values and not contains any leading/trailing spaces
mask_space = df['name'].notna() & (df['name'] != df['name'].str.strip())
print(mask_space.sum())

print(df['name'].astype(str).str.contains(r'[A-Z]', regex=True).sum())

0
0
0
0

In [290]:
# Special characters in host_name:  4713
# Numbers in host_name:  134
# Spaces in host_name :  0
# Uppercase-containing values in host_name:  102074

# Fix
df['host_name'] = (
    df['host_name']
    .str.lower()
    .str.replace(r'[^a-z\s]', '', regex=True)
)

In [291]:
# Check 

# Special Characters
print(df['host_name'].astype(str).str.contains(r'[^a-z\s]').sum())

# Numbers
print(df['host_name'].astype(str).str.contains(r'[0-9]').sum())

# Upper case containing letters
# One method
mask_upper = df['host_name'].notna() & (df['host_name'] != df['host_name'].str.lower())
print(mask_upper.sum())

# another method to check upper letter
print(df['host_name'].astype(str).str.contains(r'[A-Z]').sum())

0
0
0
0

In [292]:
# Special characters in neighbourhood_group:  0
# Numbers in neighbourhood_group:  0
# Spaces in neighbourhood_group :  0
# Uppercase-containing values in neighbourhood_group:  102568

df['neighbourhood_group'] = (
    df['neighbourhood_group']
    .str.lower()
)

print(df['neighbourhood_group'].unique())
print(df['neighbourhood_group'].value_counts())

df['neighbourhood_group'] = df['neighbourhood_group'].replace(
    {
        "manhatan" : "manhattan",
        "brookln": "brooklyn"
    }
)

print(df['neighbourhood_group'].unique())
print(df['neighbourhood_group'].value_counts())

['brooklyn' 'manhattan' 'brookln' 'manhatan' 'queens' nan 'staten island'
 'bronx']
neighbourhood_group
manhattan        43792
brooklyn         41842
queens           13267
bronx             2712
staten island      955
brookln              1
manhatan             1
Name: count, dtype: int64
['brooklyn' 'manhattan' 'queens' nan 'staten island' 'bronx']
neighbourhood_group
manhattan        43793
brooklyn         41843
queens           13267
bronx             2712
staten island      955
Name: count, dtype: int64

In [298]:
mask_upper = df['neighbourhood_group'].notna() & (df['neighbourhood_group'] != df['neighbourhood_group'].str.lower())
print(mask_upper.sum())

print(df['neighbourhood_group'].astype(str).str.contains(r'[A-Z]', regex=True).sum())

0
0

In [294]:
# Special characters in neighbourhood:  13438
# Numbers in neighbourhood:  0
# Spaces in neighbourhood :  0
# Uppercase-containing values in neighbourhood:  102583

df['neighbourhood'] = (
    df['neighbourhood']
    .str.lower()
    .str.replace(r'[^a-z\s]', '', regex=True)
)
df['neighbourhood'].value_counts()

neighbourhood
bedfordstuyvesant        7937
williamsburg             7775
harlem                   5466
bushwick                 4982
hells kitchen            3965
                         ...
rossville                   3
gerritsen beach             3
fort wadsworth              2
glen oaks                   2
chelsea staten island       1
Name: count, Length: 224, dtype: int64

In [300]:
# Fix

# Check special character
print(df['neighbourhood'].astype(str).str.contains(r'[^a-z\s]', regex=True, na=False).sum())

# Check for upper case letters
print(df['neighbourhood'].astype(str).str.contains(r'[A-Z]', regex=True, na=False).sum())

0
0

In [296]:
# Special characters in country:  0
# Numbers in country:  0
# Spaces in country :  0
# Uppercase-containing values in country:  102067

df['country'] = (
    df['country']
    .str.lower()
)

print(df['country'].unique())
print(df['country'].value_counts())

['united states' nan]
country
united states    102067
Name: count, dtype: int64

In [302]:
# Special characters in room_type:  53701
# Numbers in room_type:  0
# Spaces in room_type :  0
# Uppercase-containing values in room_type:  102599

df['room_type'] = (
    df['room_type']
    .str.lower()
    .str.replace(r'[^a-z\s]', '', regex=True)
)

print(df['room_type'].unique())
print(df['room_type'].value_counts())

['private room' 'entire homeapt' 'shared room' 'hotel room']
room_type
entire homeapt    53701
private room      46556
shared room        2226
hotel room          116
Name: count, dtype: int64

In [ ]:
# Special characters in price:  102352
# Numbers in price:  102352
# Spaces in price :  102352
# Uppercase-containing values in price:  0

df['price'] = df['price'].str.replace(r'[^0-9]', '', regex=True)
df['price'] = df['price'].fillna(df['price'].mode()[0])
df['price'] = df['price'].astype(int)

In [ ]:
# Special characters in service_fee:  102326
# Numbers in service_fee:  102326
# Spaces in service_fee :  102326
# Uppercase-containing values in service_fee:  0

df['service_fee'] = df['service_fee'].str.replace(r'[^0-9]', '', regex=True)
df['service_fee'] = df['service_fee'].fillna(df['service_fee'].mode()[0])
df['service_fee'] = df['service_fee'].astype(str).astype(int)

0         193
1          28
2         124
3          74
4          41
         ...
102594    169
102595    167
102596    198
102597    109
102598    206
Name: service_fee, Length: 102599, dtype: int64

### 6. Fix nulls in all type of columns

#####  - We have to fix nulls in every type of columns such as int64, object, float64, bool

In [315]:
df

,id,name,host_id,host_identity_verified,host_name,neighbourhood_group,neighbourhood,lat,long,country,instant_bookable,cancellation_policy,room_type,construction_year,price,service_fee,minimum_nights,number_of_reviews
0,1001254,clean quiet apt home by the park,80014485718,unconfirmed,madaline,brooklyn,kensington,40.64749,-73.97237,united states,False,strict,private room,2020.0,966,193,10.0,9.0
1,1002102,skylit midtown castle,52335172823,verified,jenna,manhattan,midtown,40.75362,-73.98377,united states,False,moderate,entire homeapt,2007.0,142,28,30.0,45.0
2,1002403,the village of harlemnew york,78829239556,NaN,elise,manhattan,harlem,40.80902,-73.94190,united states,True,flexible,private room,2005.0,620,124,3.0,0.0
3,1002755,NaN,85098326012,unconfirmed,garry,brooklyn,clinton hill,40.68514,-73.95976,united states,True,moderate,entire homeapt,2005.0,368,74,30.0,270.0
4,1003689,entire apt spacious studioloft by central park,92037596077,verified,lyndon,manhattan,east harlem,40.79851,-73.94399,united states,False,moderate,entire homeapt,2009.0,204,41,10.0,9.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102594,6092437,spare room in williamsburg,12312296767,verified,krik,brooklyn,williamsburg,40.70862,-73.94651,united states,False,flexible,private room,2003.0,844,169,1.0,0.0
102595,6092990,best location near columbia u,77864383453,unconfirmed,mifan,manhattan,morningside heights,40.80460,-73.96545,united states,True,moderate,private room,2016.0,837,167,1.0,1.0
102596,6093542,comfy bright room in brooklyn,69050334417,unconfirmed,megan,brooklyn,park slope,40.67505,-73.98045,united states,True,moderate,private room,2009.0,988,198,3.0,0.0
102597,6094094,big studioone stop from midtown,11160591270,unconfirmed,christopher,queens,long island city,40.74989,-73.93777,united states,True,strict,entire homeapt,2015.0,546,109,2.0,5.0
102598,6094647,sf luxury studio,68170633372,unconfirmed,rebecca,manhattan,upper west side,40.76807,-73.98342,united states,False,flexible,entire homeapt,2010.0,1032,206,1.0,0.0

### Type -  int64 & float64

In [ ]:
# Steps -
# - Check missing percentage
# - If 50 % or above data is missing then drop the column if it is not important
# - Or,
# - Check outlier in each column
# - If outlier present , replace NaN values with median
# - If outlier is not present, replace NaN values with mean

In [326]:
# Check missing percentage
for column in df.columns:
    if df[column].dtypes == "int64" or df[column].dtypes =="float64":
        missing_pct = np.trunc(df[column].isnull().sum()/len(df))*100
        print(column, "(", df[column].isnull().sum(), ",", missing_pct, ")")

id ( 0 , 0.0 )
host_id ( 0 , 0.0 )
lat ( 8 , 0.0 )
long ( 8 , 0.0 )
construction_year ( 214 , 0.0 )
price ( 0 , 0.0 )
service_fee ( 0 , 0.0 )
minimum_nights ( 409 , 0.0 )
number_of_reviews ( 183 , 0.0 )

In [ ]:
def check_outlers(col: str, df: pd.DataFrame) -> bool:

    Q1 = df[col].quantile(0.25) # Lower quantile -> 25 %
    Q2 = df[col].median()       # Median -> 50 %
    Q3 = df[col].quantile(0.75) # Upper auantile -> 75 %

    IQR = Q3 - Q1 # IQR