In [316]:
# - import libraries
# - load dataset
# - explore dataset

# - fix column names
# - fix individual columns

# - fix nulls in all type of columns
# - fix duplicates in all type of columns
# - fix outliers
# - fix logical intigrity
# - final exploration
# - save cleaned data

## 1 - import libraries

In [317]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

## 2 - load dataset

In [318]:
df = pd.read_csv(r"C:\Users\Arijit\Downloads\messy_customer_sales_data.csv")
df

,Customer_ID,Name,Gender,Age,City,Signup_Date,Last_Purchase_Date,Purchase_Amount,Feedback_Score,Email,Phone_Number,Country
0,CUST4371,Paul Wilson,m,52.0,KOLKATA,2025-06-26,2025-05-17,26944.0,1.0,peckvictoria@example.com,2131107701,India
1,CUST5957,Jason Thomas,M,51.0 years,NaN,2021-02-17,2025-07-22,44152.0,2.0,owensanthony@example.com,1080761560,india
2,CUST3754,Brittney Martinez,F,62.0,hyderabad,2023-11-05,2024-12-08,31745.0,2.0,tara39@example.org,8981006345,India
3,CUST2934,Brenda Pierce,FEMALE,40.0,hyderabad,2022-03-13,2025-10-02,39674.0,1.0,berrynancy@example.org,8228064204,india
4,CUST5683,Matthew Carroll,f,41.0,CHENNAI,2024-04-05,2024-12-15,NaN,8.0,denise84@example.org,2665569480,India
...,...,...,...,...,...,...,...,...,...,...,...,...
10195,CUST10767,Robert Lewis,female,35.0 years,delhi,2020-12-08,2025-01-25,24167.0,9.0,barrycrane@example.net,5004696571,InDia
10196,NaN,Diane Evans,M,53.0,bangalore,2023-12-31,2025-05-07,11639.0,7.0,lisadennis@example.net,5200349941,IND
10197,CUST6315,Joshua Martinez,m,25.0,hyderabad,2022-02-15,2025-01-11,43832.0,2.0,kelli74@example.org,8147428496,India
10198,CUST4812,Sarah Miller,FEMALE,55.0,NaN,2021-03-16,2025-05-14,18827.0,10.0,dawn84@example.org,2987564247,InDia
10199,CUST6588,David Potter,female,34.0,HYDERABAD,2020-10-12,2025-06-27,35211.0,10.0,kochjonathan@example.org,1926206725,India

## 3 - explore dataset

In [319]:
print("Total rows : ", df.shape[0])
print("Total column : ", df.shape[1])
print("Dataset dimension : ", df.ndim)

print()

print(df.info())
df.describe()

Total rows :  10200
Total column :  12
Dataset dimension :  2

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10200 entries, 0 to 10199
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Customer_ID         9177 non-null   object
 1   Name                10200 non-null  object
 2   Gender              9174 non-null   object
 3   Age                 9249 non-null   object
 4   City                9184 non-null   object
 5   Signup_Date         10200 non-null  object
 6   Last_Purchase_Date  9188 non-null   object
 7   Purchase_Amount     9179 non-null   float64
 8   Feedback_Score      9177 non-null   float64
 9   Email               10200 non-null  object
 10  Phone_Number        10200 non-null  int64
 11  Country             9468 non-null   object
dtypes: float64(2), int64(1), object(9)
memory usage: 956.4+ KB
None

       Purchase_Amount  Feedback_Score  Phone_Number
count     9.179000e+03     9177.000000  1.020000e+04
mean      2.909013e+04        5.479351  4.979974e+09
std       2.086971e+05        2.867123  2.902593e+09
min      -5.000000e+02        1.000000  9.208990e+05
25%       1.229500e+04        3.000000  2.449157e+09
50%       2.433000e+04        5.000000  4.988639e+09
75%       3.713000e+04        8.000000  7.510448e+09
max       9.999999e+06       10.000000  9.994402e+09

## 4 - fix column names

In [320]:
# print all columns
print(df.columns)

# Check how many columns are present
print(len(df.columns))

print()
# check for inconsistancy

# Check for special characters
print("\nCheck for special characters")
print(df.columns[df.columns.str.contains(r'[^A-Za-z0-9]')])


# Check for leading or trailing spaces
print("\nCheck for leading or trailing spaces")
print(df.columns[df.columns != df.columns.str.strip()])

# Check for inner spaces
print("\nCheck for inner spaces")
print(df.columns[df.columns.str.contains(r' ')])

# Check for numbers
print("\nCheck for numbers")
print(df.columns[df.columns.str.contains(r'[0-9]')])

# check for upper case letters
print("\ncheck for upper case letters")
print(df.columns[df.columns != df.columns.str.lower()])

Index(['Customer_ID', 'Name', 'Gender', 'Age', 'City', 'Signup_Date',
       'Last_Purchase_Date', 'Purchase_Amount', 'Feedback_Score', 'Email',
       'Phone_Number', 'Country'],
      dtype='object')
12


Check for special characters
Index(['Customer_ID', 'Signup_Date', 'Last_Purchase_Date', 'Purchase_Amount',
       'Feedback_Score', 'Phone_Number'],
      dtype='object')

Check for leading or trailing spaces
Index([], dtype='object')

Check for inner spaces
Index([], dtype='object')

Check for numbers
Index([], dtype='object')

check for upper case letters
Index(['Customer_ID', 'Name', 'Gender', 'Age', 'City', 'Signup_Date',
       'Last_Purchase_Date', 'Purchase_Amount', 'Feedback_Score', 'Email',
       'Phone_Number', 'Country'],
      dtype='object')

In [321]:
# Fix 
# Convert all columns to lower case letters
df.columns = df.columns.str.lower()

# Final check
print(df.columns)

Index(['customer_id', 'name', 'gender', 'age', 'city', 'signup_date',
       'last_purchase_date', 'purchase_amount', 'feedback_score', 'email',
       'phone_number', 'country'],
      dtype='object')

## 5 - fix individual columns

In [322]:
# Fix object type columns first
for column in df.columns:
    if df[column].dtype == "object":
        print(column)

customer_id
name
gender
age
city
signup_date
last_purchase_date
email
country

In [323]:
# 'customer_id' is a primary key column so it can not contain any null values and duplicates
print((df['customer_id'].isnull().sum()/len(df['customer_id']))*100) # 10 % missing
print(df['customer_id'].duplicated().sum()/len(df['customer_id'])*100)

print(df['customer_id'].isnull().sum())
print(df['customer_id'].duplicated().sum())

# Droping rows which contain nulls
df.dropna(subset=['customer_id'], inplace=True)

# Droping rows which contains duplicates
df.drop_duplicates(subset=['customer_id'], inplace=True)

# Final check
print((df['customer_id'].isnull().sum()/len(df['customer_id']))*100) # 0 % missing
print(df['customer_id'].duplicated().sum()/len(df['customer_id'])*100) # 0 % duplicates

10.029411764705882
11.754901960784315
1023
1199
0.0
0.0

In [324]:
# 'name'

# Check Total special characters
print("Total special characters : ", df['name'].str.contains(r'[^A-Za-z0-9\s]', regex=True, na=False).sum())

# Check for numbers
print("Total numbers : ", df['name'].str.contains(r'[0-9]', regex=True, na=False).sum())

# Check for new lines 
print("Total new lines : ", df['name'].str.contains(r'\n', regex=True, na=False).sum())

# Check for upper case letters
print("Total upper case letters : ", df['name'].str.contains(r'[A-Z]', regex=True, na=False).sum())

# Leading or trailing spaces
mask_space = df['name'] != df['name'].str.strip()
print("Total leading or trailing spaces : ", mask_space.sum())

Total special characters :  181
Total numbers :  0
Total new lines :  0
Total upper case letters :  9000
Total leading or trailing spaces :  0

In [325]:
# Fix 
df['name'] = (
    df['name']
    .str.lower()
    .str.replace(r'[^a-z\s]', '', regex=True)
)

In [326]:
# Final check

# Check Total special characters
print("Total special characters : ", df['name'].str.contains(r'[^A-Za-z0-9\s]', regex=True, na=False).sum())

# Check for upper case letters
print("Total upper case letters : ", df['name'].str.contains(r'[A-Z]', regex=True, na=False).sum())

Total special characters :  0
Total upper case letters :  0

In [327]:
# 'gender'
print(df['gender'].value_counts())
print(df['gender'].unique())

# Fix
df['gender'] = df['gender'].replace(
    {
        "m ":"male",
        "M":"male",
        "MALE":"male",
        "F":"female",
        "FEMALE":"female",
        "f ":"female"
    }
)

# Final check
print(df['gender'].value_counts())
print(df['gender'].unique())

gender
M         1042
f         1037
m         1031
F         1028
MALE       993
male       989
female     989
FEMALE     982
Name: count, dtype: int64
['m ' 'M' 'F' 'FEMALE' 'f ' 'male' 'MALE' 'female' nan]
gender
male      4055
female    4036
Name: count, dtype: int64
['male' 'female' nan]

In [328]:
# 'age'

# Check for special characters, letters
print("Total special characters : ", df['age'].astype(str).str.contains(r'[^0-9]').sum())

# Check data type
print("Data type : ", df['age'].dtype)

# Fix
df['age'] = (
    df['age']
    .str.replace(r'[^0-9]', '', regex=True)
    .replace(np.nan, df['age'].mode()[0])
)

df['age'] = df['age'].replace('', df['age'].mode()[0])
df['age'] = df['age'].astype(float).astype(int)

print("Total special characters : ", df['age'].astype(str).str.contains(r'[^0-9]').sum())
print("Check data type : ", df['age'].dtype)

Total special characters :  8989
Data type :  object
Total special characters :  0
Check data type :  int64

In [329]:
# city
print(df['city'].value_counts())
print(df['city'].unique())

# Fix
df['city'] = (
    df['city']
    .str.lower()
    .str.strip()
)

# Check
print(df['city'].value_counts())
print(df['city'].unique())

city
Kolkata       719
Mumbai        709
Chennai       688
Delhi         685
Bangalore     675
Hyderabad     661
CHENNAI       367
DELHI         346
MUMBAI        343
hyderabad     342
bangalore     342
KOLKATA       336
HYDERABAD     334
delhi         321
BANGALORE     320
mumbai        308
chennai       302
kolkata       297
Name: count, dtype: int64
[' KOLKATA ' nan ' hyderabad ' ' CHENNAI ' ' kolkata ' ' BANGALORE '
 ' Hyderabad ' ' HYDERABAD ' ' Mumbai ' ' chennai ' ' Delhi '
 ' bangalore ' ' Bangalore ' ' Kolkata ' ' delhi ' ' Chennai ' ' MUMBAI '
 ' DELHI ' ' mumbai ']
city
mumbai       1360
chennai      1357
delhi        1352
kolkata      1352
hyderabad    1337
bangalore    1337
Name: count, dtype: int64
['kolkata' nan 'hyderabad' 'chennai' 'bangalore' 'mumbai' 'delhi']

In [330]:
# signup_date
print(df['signup_date'].dtypes)

df['signup_date'] = pd.to_datetime(df['signup_date'], errors='coerce')
print(df['signup_date'].dtypes)

object
datetime64[ns]

In [331]:
# last_purchase_date
print(df['last_purchase_date'].dtypes)
df['last_purchase_date'] = pd.to_datetime(df['last_purchase_date'], errors='coerce')
print(df['last_purchase_date'].dtypes)

object
datetime64[ns]

In [332]:
# email
# email type : abc@gmail.com / abc12@gmail.com
# Basic cleaning

df['email'] = (
    df['email']
    .str.lower()
    .str.strip()
    .str.replace(r'[^0-9a-z@.]', '', regex=True)
)

In [333]:
# country
print(df['country'].value_counts())
print(df['country'].unique())

# Fix
valid_pattern = {
    "India":"india",
    "IND":"india",
    "InDia":"india"
}

df['country'] = df['country'].map(valid_pattern)

# final check
print(df['country'].value_counts())
print(df['country'].unique())

country
India    6303
IND       687
india     678
InDia     678
Name: count, dtype: int64
['India' 'india' nan 'InDia' 'IND']
country
india    7668
Name: count, dtype: int64
['india' nan]

In [334]:
# Now int or float type columns
for column in df.columns:
    if df[column].dtypes == "int64" or df[column].dtypes == "float64":
        print(column)

age
purchase_amount
feedback_score
phone_number

In [335]:
# Check outliers
def is_outlier(col: str, df: pd.DataFrame) -> bool:

    Q1 = df[col].quantile(0.25)
    Q2 = df[col].median()
    Q3 = df[col].quantile(0.75)

    IQR = Q3 - Q1

    lower_limit = Q1 - (IQR * 1.5)
    upper_limit = Q3 + (IQR * 1.5)

    if len(df.loc[df[col] > upper_limit]) > 0 or len(df.loc[df[col] < lower_limit]) > 0:
        return True
    else:
        return False

In [336]:
# purchase_amount
print((df[['purchase_amount', 'feedback_score']].isnull().sum()/len(df[['purchase_amount', 'feedback_score']]))*100)

# Fix
columns = ['purchase_amount', 'feedback_score']

for cols in columns:
    if is_outlier(col=cols, df=df):
        df[cols] = df[cols].replace(np.nan, df[cols].median())
    else:
        df[cols] = df[cols].replace(np.nan, df[cols].mean())

# Final check
print((df[['purchase_amount', 'feedback_score']].isnull().sum()/len(df[['purchase_amount', 'feedback_score']]))*100)

purchase_amount    10.066667
feedback_score      9.855556
dtype: float64
purchase_amount    0.0
feedback_score     0.0
dtype: float64

In [337]:
# phone number
# For data cleaning
# If you're cleaning the dataset, don't treat phone number as an integer.

# To check in phone numbers
# This is important because phone numbers can have:
"""
# leading zeros
# country codes (+91)
# spaces
# hyphens
# parentheses
"""

# convert it's data type for better analysis
df['phone_number'] = df['phone_number'].astype(str)

# Leading zeros
zeros_mask = df['phone_number'].str.startswith('0', na=False)
print(zeros_mask.sum())

# country code (+91)
country_code_mask = df['phone_number'].str.startswith('+91', na=False)
print(country_code_mask.sum())

# length > 10
greater_than_ten_mask = df['phone_number'].str.len() > 10
print(greater_than_ten_mask.sum())


df['phone_number'] = df['phone_number'].astype(int)

0
0
0

In [338]:
df

,customer_id,name,gender,age,city,signup_date,last_purchase_date,purchase_amount,feedback_score,email,phone_number,country
0,CUST4371,paul wilson,male,520,kolkata,2025-06-26,2025-05-17,26944.0,1.0,peckvictoria@example.com,2131107701,india
1,CUST5957,jason thomas,male,510,NaN,2021-02-17,2025-07-22,44152.0,2.0,owensanthony@example.com,1080761560,NaN
2,CUST3754,brittney martinez,female,620,hyderabad,2023-11-05,2024-12-08,31745.0,2.0,tara39@example.org,8981006345,india
3,CUST2934,brenda pierce,female,400,hyderabad,2022-03-13,2025-10-02,39674.0,1.0,berrynancy@example.org,8228064204,NaN
4,CUST5683,matthew carroll,female,410,chennai,2024-04-05,2024-12-15,24268.0,8.0,denise84@example.org,2665569480,india
...,...,...,...,...,...,...,...,...,...,...,...,...
10193,CUST6352,isaiah terry,female,260,kolkata,2023-03-04,2025-06-30,43655.0,6.0,lopezleonard@example.net,7694723210,india
10194,CUST6146,cody thompson,female,400,NaN,2024-08-21,2024-10-26,35101.0,1.0,mitchellrivera@example.net,6380823112,india
10195,CUST10767,robert lewis,female,350,delhi,2020-12-08,2025-01-25,24167.0,9.0,barrycrane@example.net,5004696571,india
10197,CUST6315,joshua martinez,male,250,hyderabad,2022-02-15,2025-01-11,43832.0,2.0,kelli74@example.org,8147428496,india
10198,CUST4812,sarah miller,female,550,NaN,2021-03-16,2025-05-14,18827.0,10.0,dawn84@example.org,2987564247,india

# 6 - fix nulls in all type of columns

In [339]:
# Object type columns
for column in df.columns:
    if df[column].dtypes == "object":
        if column == "email":
            continue

        else:
            missing_pct = (df[column].isnull().sum()/len(df[column]))*100

            if missing_pct <= 10:
                df[column] = df[column].replace(np.nan, df[column].mode()[0])
            else:
                df[column] = df[column].replace(np.nan, 'unknown')

In [ ]:
# Data type columns
for column in df.columns:
    if df[column].dtypes == '<M8[ns]':
        missing_pct = (df[column].isnull().sum()/len(df[column]))*100
        print(column, "=", missing_pct)

signup_date = 0.0
last_purchase_date = 10.033333333333333