In [309]:
# IMPORTING ESSENTIAL LIBRARIES
import numpy as np
import pandas as pd

In [ ]:
# LOAD THE DATASET
df = pd.read_csv(r"C:\Users\Arijit\Downloads\marketing_campaign_data_messy.csv")
df

,Campaign_ID,Campaign_Name,Start_Date,End_Date,Channel,Impressions,Clicks,Spend,Conversions,Active,Clicks,Campaign_Tag
0,CMP-00001,Q4_Summer_CMP-00001,2023-11-24 00:00:00,2023-12-13,TikTok,16795,197,$102.82,20.0,Y,NaN,TI
1,CMP-00002,Q1_Launch_CMP-00002,2023-05-06 00:00:00,2023-05-12,Facebook,1860,30,24.33,1.0,0,NaN,FA
2,CMP-00003,Q3_Winter_CMP-00003,2023-12-13 00:00:00,2023-12-20,Email,77820,843,1323.39,51.0,No,NaN,EM
3,CMP-00004,Q1_BlackFriday_CMP-00004,2023-10-30,2023-11-03,TikTok,55886,2019,2180.38,135.0,True,NaN,TI
4,CMP-00005,Q2_Winter_CMP-00005,2023-04-22 00:00:00,2023-04-23,Facebook,7265,169,252.44,30.0,Yes,NaN,FA
...,...,...,...,...,...,...,...,...,...,...,...,...
2015,CMP-00400,Q3_Summer_CMP-00400,2023-10-31 00:00:00,2023-11-13,TikTok,30592,586,$503.95,77.0,1,NaN,TI
2016,CMP-01255,Q4_Summer_CMP-01255,2023-09-01 00:00:00,2023-09-26,Google Ads,20097,897,1641.0,162.0,0,NaN,GO
2017,CMP-01050,Q2_Launch_CMP-01050,2023-02-09 00:00:00,2023-02-21,Instagram,33254,1117,883.82,214.0,0,NaN,IN
2018,CMP-01118,Q4_Winter_CMP-01118,2023-03-30 00:00:00,2023-04-27,Facebook,68728,2960,4198.5,591.0,Yes,NaN,FA
2019,CMP-01554,Q4_Launch_CMP-01554,2023-06-26 00:00:00,2023-07-09,Email,96402,1090,1315.59,66.0,Y,NaN,EM

In [311]:
# EXPLORING THE DATASET
print("Total rows : ", df.shape[0])
print("Total columns : ", df.shape[1])
print("Data dimension : ", df.ndim)
print("Data size : ", df.size)

print()

# SUMMARY STATISTICS
df.info()

Total rows :  2020
Total columns :  12
Data dimension :  2
Data size :  24240

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2020 entries, 0 to 2019
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0    Campaign_ID   2020 non-null   object
 1   Campaign_Name  2020 non-null   object
 2   Start_Date     2020 non-null   object
 3   End_Date       2020 non-null   object
 4   Channel        1919 non-null   object
 5   Impressions    2020 non-null   int64
 6   Clicks         2020 non-null   int64
 7   Spend          2020 non-null   object
 8   Conversions    1820 non-null   float64
 9   Active         2020 non-null   object
 10  Clicks         40 non-null     float64
 11  Campaign_Tag   2020 non-null   object
dtypes: float64(2), int64(2), object(8)
memory usage: 189.5+ KB

In [ ]:
# CLEANING COLUMNS
# IDENTIFYING COLUMNS WHICH CONTAINS SPACES, SPECIAL CHARACTERS, LOWER-CASE, UPPER-CASE.

print(df.columns[df.columns == r'[0-9]'])               # CHECKING FOR DIGITS FROM 0 TO 9
print(df.columns[df.columns != df.columns.str.strip()]) # CHECKING IF ANY COLUMN CONTAINS SPACES
print(df.columns[df.columns != df.columns.str.lower()]) # CHECKING IF ANY COLUMN CONTAINS UPPER CASE

# CONVERTING EACH COLUMNS TO IT'S LOWER CASE
df.columns = df.columns.str.lower() # CONVERTING EACH COLUMN NAMES TO LOWER CASE
df.columns = df.columns.str.strip() # REMOVING SPACES FROM EACH COLUMN

df.columns

Index([], dtype='object')
Index([' Campaign_ID ', 'Clicks '], dtype='object')
Index([' Campaign_ID ', 'Campaign_Name', 'Start_Date', 'End_Date', 'Channel',
       'Impressions', 'Clicks ', 'Spend', 'Conversions', 'Active', 'Clicks',
       'Campaign_Tag'],
      dtype='object')

Index(['campaign_id', 'campaign_name', 'start_date', 'end_date', 'channel',
       'impressions', 'clicks', 'spend', 'conversions', 'active', 'clicks',
       'campaign_tag'],
      dtype='object')

In [ ]:
# Check list :

# Contains any non-digit	            df['spend'].str.contains(r'[^0-9]', na=False)
# Contains only digits	                df['spend'].str.fullmatch(r'\d+', na=False)
# Contains letters	                    df['spend'].str.contains(r'[A-Za-z]', na=False)
# Contains special characters	        df['spend'].str.contains(r'[^A-Za-z0-9]', na=False)


# CHECKING COLUMNS
contains_dollar = df['spend'].astype(str).str.contains(r'\$', na=False)
contains_spaces = df['spend'].astype(str).str.contains(r' ', na=False)
contains_only_digits = df['spend'].astype(str).str.fullmatch(r'\d+', na=False)
contains_letters = df['spend'].astype(str).str.contains(r'[A-Za-z]', na=False)
contains_special_characters = df['spend'].astype(str).str.contains(r'[^A-Za-z0-9]', na=False)

print("Contains $ :", contains_dollar.sum())
print("Contains spaces :", contains_spaces.sum())
print("Contains only digits :", contains_only_digits.sum())
print("Contains letters :", contains_letters.sum())
print("Contains special characters :", contains_special_characters.sum())

print()

# REMOVING $
df['spend'] = df['spend'].str.replace('$', "")
contains_dollar = df['spend'].astype(str).str.contains(r'\$', na=False)
print("Contains $ : ", contains_dollar.sum())

Contains $ : 298
Contains spaces : 0
Contains only digits : 0
Contains letters : 0
Contains special characters : 2020

Contains $ :  0

##### 1. Replace function is used for column containing values
##### 2. Rename function is used for renaming column names

In [ ]:
# IMPROVING CATAGORICAL TYPO

# CHEACKING HOW MANY UNIQUE VALUES ARE PRESENT
print(df['channel'].value_counts()) # OCCURRENCE OF EACH UNIQUE VALUE
print()
print(df['channel'].unique()) # EACH UNIQUE VALUES
print()
print("\nTotal unique values : ", df['channel'].nunique()) # NUMBER OF UNIQUE VALUES

# CLEANING TYPOS
df['channel'] = df['channel'].replace({
    "Tik_Tok":"TikTok",
    "Facebok":"Facebook",
    "E-mail":"Email",
    "Gogle":"Google Ads",
    "Insta_gram":"Instagram"  
})

print(df['channel'].value_counts())
print()
print(df['channel'].unique())
print()
print("Total unique values : ", df['channel'].nunique())

channel
TikTok        399
Facebook      391
Email         359
Google Ads    346
Instagram     340
E-mail         21
Insta_gram     19
Tik_Tok        16
Gogle          14
Facebok        14
Name: count, dtype: int64

['TikTok' 'Facebook' 'Email' 'Instagram' 'Google Ads' 'E-mail' nan 'Gogle'
 'Tik_Tok' 'Facebok' 'Insta_gram']


Total unique values :  10
channel
TikTok        415
Facebook      405
Email         380
Google Ads    360
Instagram     359
Name: count, dtype: int64

['TikTok' 'Facebook' 'Email' 'Instagram' 'Google Ads' nan]

Total unique values :  5

C:\Users\Arijit\AppData\Local\Temp\ipykernel_8040\837264591.py:11: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['channel'].replace({

In [ ]:
# FIXING BOOLEAN COLUMNS

print(df['active'].value_counts()) # NUMBER OF OCCURRENCE OF EACH VALUES 
print(df['active'].unique())       # EACH UNIQUE VALUES
print(df['active'].nunique())      # NUMBER OF UNIQUE VALUES

df['active'] = df['active'].replace(
    {
        "1":"True",
        "Yes":"True",
        "Y":"True",
        "0":"False",
        "No":"False"
})

print(df['active'].value_counts())
print(df['active'].unique())
print(df['active'].nunique())

active
1        319
Yes      306
True     297
No       291
False    281
Y        273
0        253
Name: count, dtype: int64
['Y' '0' 'No' 'True' 'Yes' '1' 'False']
7
active
True     1195
False     825
Name: count, dtype: int64
['True' 'False']
2

### DATE PARSING

In [318]:
# DATE PARSING

print(df['start_date'].dtype)

df['start_date'] = pd.to_datetime(df['start_date'], errors='coerce')
df['end_date'] = pd.to_datetime(df['end_date'], errors='coerce')

df['start_date'].dtypes
df['end_date'].dtypes

datetime64[ns]

dtype('<M8[ns]')

In [ ]:
# DROPPING DUPLICATE COLUMNS
# THERE ARE TWO DUPLICATED COLUMNS => clicks
df = df.loc[:, ~df.columns.duplicated()]
df

,campaign_id,campaign_name,start_date,end_date,channel,impressions,clicks,spend,conversions,active,campaign_tag
0,CMP-00001,Q4_Summer_CMP-00001,2023-11-24,2023-12-13,TikTok,16795,197,102.82,20.0,True,TI
1,CMP-00002,Q1_Launch_CMP-00002,2023-05-06,2023-05-12,Facebook,1860,30,24.33,1.0,False,FA
2,CMP-00003,Q3_Winter_CMP-00003,2023-12-13,2023-12-20,Email,77820,843,1323.39,51.0,False,EM
3,CMP-00004,Q1_BlackFriday_CMP-00004,NaT,2023-11-03,TikTok,55886,2019,2180.38,135.0,True,TI
4,CMP-00005,Q2_Winter_CMP-00005,2023-04-22,2023-04-23,Facebook,7265,169,252.44,30.0,True,FA
...,...,...,...,...,...,...,...,...,...,...,...
2015,CMP-00400,Q3_Summer_CMP-00400,2023-10-31,2023-11-13,TikTok,30592,586,503.95,77.0,True,TI
2016,CMP-01255,Q4_Summer_CMP-01255,2023-09-01,2023-09-26,Google Ads,20097,897,1641.0,162.0,False,GO
2017,CMP-01050,Q2_Launch_CMP-01050,2023-02-09,2023-02-21,Instagram,33254,1117,883.82,214.0,False,IN
2018,CMP-01118,Q4_Winter_CMP-01118,2023-03-30,2023-04-27,Facebook,68728,2960,4198.5,591.0,True,FA
2019,CMP-01554,Q4_Launch_CMP-01554,2023-06-26,2023-07-09,Email,96402,1090,1315.59,66.0,True,EM

### LOGICAL INTIGRITY

In [338]:
# NOW WE HAVE TO COMPARE CLICKS WITH IMPRESSIONS
# IMPRESSION = How many times a object shown or displayed on the screen
# CLICKS = How many times someone clicking that object
# IT IS FIXED THAT IMPRESSIONS >= CLICKS.
# EXAMPLE : IMPRESSION = 100 , CLICK = 50. WE CAN UNDERSTAND THAT 50 TIMES THAT OBJECT IS CLICKED OUT OF 100

impossible_mask = df['clicks'] > df['impressions']
df.loc[impossible_mask, ['clicks', 'impressions']]

Empty DataFrame
Columns: [clicks, impressions]
Index: []

In [ ]:
# IT IS SIMPLE LOGIC THAT START DATE WILL ALWAYS BE LESS THAN END DATE.
# GETTING THOSE ROWS WHERE END DATE IS LESS THAN START DATE

df.loc[df['end_date'] < df['start_date']]

,campaign_id,campaign_name,start_date,end_date,channel,impressions,clicks,spend,conversions,active,campaign_tag
23,CMP-00024,Q4_Winter_CMP-00024,2023-05-06,2023-05-01,Instagram,29693,995,1793.94,179.0,False,IN
54,CMP-00055,Q1_Launch_CMP-00055,2023-09-01,2023-08-27,Google Ads,18159,471,563.31,33.0,False,GO
71,CMP-00072,Q1_Summer_CMP-00072,2023-02-01,2023-01-27,Email,66697,1340,2090.74,NaN,True,EM
156,CMP-00157,Q3_Launch_CMP-00157,2023-12-06,2023-12-01,TikTok,82734,2912,4690.79,NaN,True,TI
200,CMP-00201,Q3_BlackFriday_CMP-00201,2023-01-11,2023-01-06,Instagram,69840,2185,1467.55,272.0,True,IN
218,CMP-00219,Q3_Winter_CMP-00219,2023-10-03,2023-09-28,TikTok,39623,1689,1094.26,241.0,False,TI
221,CMP-00222,Q1_Winter_CMP-00222,2023-08-26,2023-08-21,TikTok,47717,691,985.25,127.0,True,TI
280,CMP-00281,Q4_Summer_CMP-00281,2023-12-10,2023-12-05,Email,32616,1161,1584.67,229.0,True,EM
303,CMP-00304,Q4_Winter_CMP-00304,2023-05-17,2023-05-12,Google Ads,39360,867,778.61,137.0,True,GO
346,CMP-00347,Q1_Summer_CMP-00347,2023-11-07,2023-11-02,Google Ads,95660,1767,1384.81,NaN,False,GO
466,CMP-00467,Q2_Launch_CMP-00467,2023-04-10,2023-04-05,NaN,75740,872,1242.96,144.0,True,XX
641,CMP-00642,Q1_Winter_CMP-00642,2023-07-21,2023-07-16,Facebook,12174,462,623.39,79.0,True,FA
693,CMP-00694,Q2_Summer_CMP-00694,2023-10-15,2023-10-10,Google Ads,5748,260,471.3,13.0,False,GO
802,CMP-00803,Q3_Winter_CMP-00803,2023-10-24,2023-10-19,TikTok,61100,928,577.68,74.0,True,TI
803,CMP-00804,Q3_BlackFriday_CMP-00804,2023-04-11,2023-04-06,TikTok,99142,3715,7008.09,676.0,True,INVALID
804,CMP-00805,Q4_Summer_CMP-00805,2023-05-06,2023-05-01,NaN,10860,149,147.32,11.0,True,XX
865,CMP-00866,Q1_Summer_CMP-00866,2023-10-14,2023-10-09,TikTok,76745,1286,821.43,64.0,True,TI
932,CMP-00933,Q4_Launch_CMP-00933,2023-11-27,2023-11-22,TikTok,96257,1492,1757.77,NaN,True,TI
960,CMP-00961,Q2_Summer_CMP-00961,2023-07-30,2023-07-25,NaN,36854,1286,1133.47,80.0,False,XX
975,CMP-00976,Q4_Launch_CMP-00976,2023-10-17,2023-10-12,Email,8561,100,125.37,7.0,True,EM
985,CMP-00986,Q4_BlackFriday_CMP-00986,2023-06-06,2023-06-01,TikTok,82264,970,1922.18,94.0,True,TI
1014,CMP-01015,Q1_BlackFriday_CMP-01015,2023-08-04,2023-07-30,Instagram,25818,589,684.26,85.0,False,IN
1021,CMP-01022,Q1_Summer_CMP-01022,2023-11-24,2023-11-19,Email,80579,2424,2906.8,484.0,True,EM
1084,CMP-01085,Q3_BlackFriday_CMP-01085,2023-01-16,2023-01-11,Instagram,37159,711,414.6,55.0,True,IN
1185,CMP-01186,Q1_BlackFriday_CMP-01186,2023-10-21,2023-10-16,Facebook,76993,3761,5910.87,239.0,True,FA
1339,CMP-01340,Q3_Launch_CMP-01340,2023-12-06,2023-12-01,Facebook,67358,1012,1217.62,110.0,False,FA
1360,CMP-01361,Q3_BlackFriday_CMP-01361,2023-09-25,2023-09-20,Instagram,95914,3783,3148.5,307.0,True,IN
1462,CMP-01463,Q3_BlackFriday_CMP-01463,2023-04-03,2023-03-29,Instagram,48304,2324,4090.23,NaN,True,IN
1497,CMP-01498,Q1_BlackFriday_CMP-01498,2023-04-16,2023-04-11,Facebook,45623,1395,1936.72,82.0,False,FA
1633,CMP-01634,Q1_Winter_CMP-01634,2023-04-12,2023-04-07,NaN,81435,1509,2104.53,294.0,False,XX
1759,CMP-01760,Q3_Summer_CMP-01760,2023-05-11,2023-05-06,Email,76418,1942,3829.18,179.0,True,EM
1801,CMP-01802,Q2_Launch_CMP-01802,2023-04-30,2023-04-25,Google Ads,91874,4170,5308.23,679.0,False,GO
1941,CMP-01942,Q1_Winter_CMP-01942,2023-07-12,2023-07-07,Google Ads,53326,2057,2926.28,379.0,True,GO
1952,CMP-01953,Q4_Winter_CMP-01953,2023-09-26,2023-09-21,Email,63768,1939,2297.9,111.0,False,EM

In [ ]:
# HOW MANY ROWS ARE AFFECTED
time_travel_mask = df['end_date'] < df['start_date']
df.loc[time_travel_mask, ['end_date', 'start_date']]

# FIXING 
df.loc[time_travel_mask, 'end_date'] = df.loc[time_travel_mask, 'start_date'] + pd.Timedelta(days=30)

       end_date start_date
23   2023-06-05 2023-05-06
54   2023-10-01 2023-09-01
71   2023-03-03 2023-02-01
156  2024-01-05 2023-12-06
200  2023-02-10 2023-01-11
218  2023-11-02 2023-10-03
221  2023-09-25 2023-08-26
280  2024-01-09 2023-12-10
303  2023-06-16 2023-05-17
346  2023-12-07 2023-11-07
466  2023-05-10 2023-04-10
641  2023-08-20 2023-07-21
693  2023-11-14 2023-10-15
802  2023-11-23 2023-10-24
803  2023-05-11 2023-04-11
804  2023-06-05 2023-05-06
865  2023-11-13 2023-10-14
932  2023-12-27 2023-11-27
960  2023-08-29 2023-07-30
975  2023-11-16 2023-10-17
985  2023-07-06 2023-06-06
1014 2023-09-03 2023-08-04
1021 2023-12-24 2023-11-24
1084 2023-02-15 2023-01-16
1185 2023-11-20 2023-10-21
1339 2024-01-05 2023-12-06
1360 2023-10-25 2023-09-25
1462 2023-05-03 2023-04-03
1497 2023-05-16 2023-04-16
1633 2023-05-12 2023-04-12
1759 2023-06-10 2023-05-11
1801 2023-05-30 2023-04-30
1941 2023-08-11 2023-07-12
1952 2023-10-26 2023-09-26

In [ ]:
# FIXED
df.loc[df['end_date'] < df['start_date']]

Empty DataFrame
Columns: [campaign_id, campaign_name, start_date, end_date, channel, impressions, clicks, spend, conversions, active, campaign_tag]
Index: []

In [354]:
# OUTLIER TREATMENT

# CONVERTING DATA TYPES
df['spend'] = df['spend'].astype(str).astype(float).astype(int)
df['spend'].dtypes

Q1 = df['spend'].quantile(0.25)
Q3 = df['spend'].quantile(0.75)

IQR = Q3-Q1

upper_limit = Q3 + (IQR * 1.5)
lower_limit = Q1 - (IQR * 1.5)

print(upper_limit)

df.loc[df['spend'] > upper_limit] = upper_limit
df.loc[df['spend'] < lower_limit] = lower_limit

5619.75

In [ ]:
# CHECKING IF OUTLIER STILL PRESENT OR NOT.
# FIXED
print(df.loc[df['spend'] > upper_limit])
print(df.loc[df['spend'] < lower_limit])

Empty DataFrame
Columns: [campaign_id, campaign_name, start_date, end_date, channel, impressions, clicks, spend, conversions, active, campaign_tag]
Index: []
Empty DataFrame
Columns: [campaign_id, campaign_name, start_date, end_date, channel, impressions, clicks, spend, conversions, active, campaign_tag]
Index: []